### ISSUE TITLE
some error with proxy

### ISSUE THREAD

**Issue by wizzzz9** [shahzain345/Discord-MultiToolPY#1]
When I try to use proxy I get this:
I'm sure that my proxies are working

` Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\backends\sync.py", line 82, in connect_tcp
    sock = socket.create_connection(
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\socket.py", line 843, in create_connection
    raise err
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\http_proxy.py", line 255, in handle_request
    connect_response = self._connection.handle_request(
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\backends\sync.py", line 82, in connect_tcp
    sock = socket.create_connection(
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\asus\Desktop\2\Discord-MultiToolPY-main\main.py", line 375, in <module>
    menu()
  File "C:\Users\asus\Desktop\2\Discord-MultiToolPY-main\main.py", line 198, in menu
    req1 = getInviteInfo(rawInvite)
  File "C:\Users\asus\Desktop\2\Discord-MultiToolPY-main\utils.py", line 68, in getInviteInfo
    res = client.get(f'https://discord.com/api/v9/invites/{rawInvite}?with_counts=true', headers={
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1025, in get
    return self.request(
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 889, in send
    response = self._send_handling_auth(
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

Process finished with exit code 1`

**Comment by shahzain345** [comment]
Can you tell me what protocol do your proxies use?

**Comment by wizzzz9** [comment]
@shahzain345  http also I tried https

**Comment by wizzzz9** [comment]
@shahzain345 I noticed that this problem is not present when using the SingleDM function but with Joiner Server it is not working

**Comment by shahzain345** [comment]
i am using python 3.9.8 also message me on guilded and I'll be happy to help you.
